BetterBuys/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BetterBuys.Models
{
    public class Cart : BaseEntity
    {
        public string ShippingAddress { get; private set; }
        public DateTime CreatedOn { get; private set; }
        public int Status { get; private set; }

        public virtual ICollection<CartProduct> CartProducts { get; set; }
    }
}

BetterBuys/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BetterBuys.Data;
using BetterBuys.Interfaces;
using BetterBuys.Models;
using BetterBuys.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace BetterBuys.Pages.Cart
{

    public class CartModel : PageModel
    {

        private readonly IProductVMService _productVMService;
        private readonly StoreDbContext _db;

        public CartModel(IProductVMService productVMService, StoreDbContext db)
        {
            _productVMService = productVMService;
            _db = db;
            
        }

        public ProductIndexVM ProductIndex { get; set; } = new ProductIndexVM();
        public List<ProductVM> productsInCart { get; set; } = new List<ProductVM>();
        public void OnGet()
        {
            ProductIndex = _productVMService.GetProductsVM(HttpContext, null);

            if (HttpContext.Session.GetInt32("cartId") != null)
            {
                productsInCart = (from p in ProductIndex.Products
                                  join cp in _db.CartProducts on p.Id equals cp.ProductId
                                  where cp.CartId == (int)HttpContext.Session.GetInt32("cartId")
                                  select p).ToList();
            }
        }

        // Calculate total price without delivery fee
        public decimal CalTotal(List<ProductVM> productList)
        {
            decimal total = 0;
            foreach(var item in productList)
            {
                total += (item.Price * item.Quantity);
            }
            return total;
        }

        // method of the update
        public async Task<IActionResult> OnPostUpdate(int quantity, int? categoryId, int? productId)
        {
            ProductIndex = _productVMService.GetProductsVM(HttpContext, categoryId);

            int? cartId = HttpContext.Session.GetInt32("cartId");

            var cartProduct = await _db.CartProducts.Where(cp => cp.CartId == cartId && cp.ProductId == productId).FirstOrDefaultAsync();

            if(cartProduct != null)
            {
                cartProduct.updateQuantity(quantity);
                await _db.SaveChangesAsync();
            }

            return RedirectToPage("Cart");
        }

        //method for the delete
        public async Task<IActionResult> OnPostDelete(int? productId)
        {
            int? cartId = HttpContext.Session.GetInt32("cartId");
            var cartproducts = await _db.CartProducts.Where(cp => cp.CartId == cartId && cp.ProductId == productId).FirstOrDefaultAsync();

            if (cartproducts == null)
            {
                return NotFound();
            }
            _db.CartProducts.Remove(cartproducts);
            await _db.SaveChangesAsync();

            return RedirectToPage("Cart");
        }
    }
}

BetterBuys/Pages/Checkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using BetterBuys.Data;
using BetterBuys.Interfaces;
using BetterBuys.Models;
using BetterBuys.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace BetterBuys.Pages.Checkout
{
    [Authorize]
    public class CheckoutModel : PageModel
    {
        [BindProperty, Required, RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only"), MinLength(2, ErrorMessage = "First Name must contain at least 2 characters"),
        MaxLength(50, ErrorMessage = "First Name must not exceed 50 characters")]
        public string FirstName { get; set; }
        [BindProperty, Required, RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only"), MinLength(2, ErrorMessage = "Last Name must contain at least 2 characters"),
        MaxLength(50, ErrorMessage = "Last Name must not exceed 50 characters")]
        public string LastName { get; set; }
        [BindProperty, Required, MaxLength(100, ErrorMessage = "Address must not exceed 100 characters")]
        public string Address { get; set; }
        public string Apartment { get; set; }
        [BindProperty, Required, MaxLength(35, ErrorMessage = "City must not exceed 35 characters")]
        public string City { get; set; }
        [BindProperty, Required]
        public string Country { get; set; }
        [BindProperty, Required]
        public string Province { get; set; }
        [BindProperty, Required, RegularExpression("^[a-zA-Z]{1}[0-9]{1}[a-zA-Z]{1}[ ]?[0-9]{1}[a-zA-Z]{1}[0-9]{1}$",
        ErrorMessage = "Invalid Postal Code")]
        public string PostalCode { get; set; }
        [BindProperty, Required, Phone(ErrorMessage = "Invalid Phone Number")]
        public string Phone { get; set; }
        [BindProperty, Required, RegularExpression("^((?!(0))[0-9]{16})$", ErrorMessage = "Invalid Card Number")]
        public string CardNumber { get; set; }
        [BindProperty, Required, RegularExpression(@"^[a-zA-Z ]+$", ErrorMessage = "Use letters only"), MinLength(2, ErrorMessage = "Cardholder Name must contain at least 2 characters"),
         MaxLength(50, ErrorMessage = "Cardholder Name must not exceed 50 characters")]
        public string CardHolderName { get; set; }
        [BindProperty, Required, RegularExpression("^((0[1-9])|(1[0-2]))/((2[0-9][2-9][0-9])|(3000))$", ErrorMessage = "Invalid Expiration Date")]
        public string ExpirationDate { get; set; }

        private readonly IProductVMService _productVMService;
        private readonly StoreDbContext _db;
        
        public CheckoutModel(IProductVMService productVMService, StoreDbContext db)
        {
            _productVMService = productVMService;
            _db = db;
        }
        public ProductIndexVM ProductIndex { get; set; } = new ProductIndexVM();
        public List<ProductVM> productsInCart { get; set; } = new List<ProductVM>();
        public void OnGet()
        {
            ProductIndex = _productVMService.GetProductsVM(HttpContext, null);
            if (HttpContext.Session.GetInt32("cartId") != null)
            {
                productsInCart = (from p in ProductIndex.Products
                                  join cp in _db.CartProducts on p.Id equals cp.ProductId
                                  where cp.CartId == (int)HttpContext.Session.GetInt32("cartId")
                                  select p).ToList();
            }
        }

        public CheckoutInfo checkoutInfo;
        public async Task<IActionResult> OnPost()
        {
            ProductIndex = _productVMService.GetProductsVM(HttpContext, null);
            int? cartId = HttpContext.Session.GetInt32("cartId");

            if (cartId != null)
            {
                productsInCart = (from p in ProductIndex.Products
                                  join cp in _db.CartProducts on p.Id equals cp.ProductId
                                  where cp.CartId == cartId
                                  select p).ToList();
            }
            checkoutInfo = new CheckoutInfo(HttpContext.Session.GetInt32("cartId"), FirstName, LastName, Address, Apartment, City,
                             Country, Province, PostalCode, Phone, CardNumber, CardHolderName, ExpirationDate);

            if (!ModelState.IsValid)
            {
                return Page();
            }
            else
            {
                await _db.CheckoutInfos.AddAsync(checkoutInfo);
                ShoppingCart cart = await _db.Carts.Where(c => c.Id == cartId).FirstOrDefaultAsync();
                cart.setStatus(1);
                await _db.SaveChangesAsync();
                HttpContext.Session.Remove("cartId");
                return RedirectToPage("Confirmation");
            }
        }
        

        // Calculate total price before delivery fee
        public decimal CalTotal(List<ProductVM> productList)
        {
            decimal total = 0;
            foreach (var item in productList)
            {
                total += (item.Price * item.Quantity);
            }
            return total;
        }
    }
}

BetterBuys/Pages/Checkout/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BetterBuys.Data;
using BetterBuys.Interfaces;
using BetterBuys.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace BetterBuys.Pages.Checkout
{
    public class IndexModel : PageModel
    {

        private readonly IProductVMService _productVMService;

        public IndexModel(IProductVMService productVMService)
        {
            _productVMService = productVMService;
        }

        public ProductIndexVM ProductIndex { get; set; } = new ProductIndexVM();
        public void OnGet(int? categoryId)
        {
            ProductIndex = _productVMService.GetProductsVM(categoryId);
        }
    }
}

BetterBuys/Pages/Confirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BetterBuys.Interfaces;
using BetterBuys.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BetterBuys.Pages
{
    public class ConfirmationModel : PageModel
    {
        private readonly IProductVMService _productVMService;
        public ConfirmationModel(IProductVMService productVMService)
        {
            _productVMService = productVMService;
        }
        public ProductIndexVM ProductIndex { get; set; } = new ProductIndexVM();
        public void OnGet()
        {
            ProductIndex = _productVMService.GetProductsVM(HttpContext, null);
        }
    }
}

BetterBuys/Pages/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using BetterBuys.Data;
using BetterBuys.Interfaces;
using BetterBuys.Models;
using BetterBuys.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BetterBuys.Pages
{
    public class DetailModel : PageModel
    {
        private readonly IProductVMService _productVMService;
        private readonly StoreDbContext _db;
        public string warningMsg = "";
        Claim user;
        public DetailModel(IProductVMService productVMService, StoreDbContext db, IHttpContextAccessor httpContextAccessor)
        {
            _productVMService = productVMService;
            _db = db;
            user = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier);
        }

        public ProductIndexVM ProductIndex { get; set; } = new ProductIndexVM();
        public ProductVM ProductDetail { get; private set; }

        public void OnGet(int productId)
        {
            ProductDetail = _productVMService.GetProduct(productId);
            ProductIndex = _productVMService.GetProductsVM(HttpContext, null);
        }

        public ShoppingCart Cart { get; set; }

        // Add a product to the cart
        public IActionResult OnPost(int productId, ProductVM product)
        {
            ProductDetail = _productVMService.GetProduct(productId);

            if (product?.Id == null)
            {
                return RedirectToPage("/Index");
            }

            //need to validate against user or session
            int? cartId = HttpContext.Session.GetInt32("cartId");

            if (cartId == null) //new cart
            {
                Cart = new ShoppingCart(user == null ? null : user.Value);
                _db.Carts.Add(Cart);
                _db.SaveChanges();
                cartId = Cart.Id;
            }

            //update existing prod in existing cart
            CartProduct cp;
            //add new prod to existing cart 

            cp = _db.CartProducts.Where(cp => cp.CartId == cartId && cp.ProductId == product.Id)
                .FirstOrDefault();

            if (cp == null) //product not in this cart yet
            {
                cp = new CartProduct((int)cartId, product.Id, product.Price, product.Quantity);
                _db.CartProducts.Add(cp);

            }
            else //product is already in cart
            {
                if ((cp.Quantity + product.Quantity) <= 50) // Add quantity if won't exceed 50
                {
                    cp.AddQuantity(product.Quantity);
                }
                else if(cp.Quantity == 50) // Display alert for exactly 50
                {
                    warningMsg = "You have reach the quantity limit!";
                }
                else // Display alert if the added quantity will exceed 50
                {
                    warningMsg = "Reach quantity limit. You can add " + (50 - cp.Quantity) + " more of " + product.Name + "!";
                }
            }

            _db.SaveChanges();

            HttpContext.Session.SetInt32("cartId", (int)cartId);

            ProductIndex = _productVMService.GetProductsVM(HttpContext, null);

            return Page();
        }
    }
}

BetterBuys/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using BetterBuys.Interfaces;
using BetterBuys.ViewModels;

namespace BetterBuys.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        private readonly IProductVMService _productVMService;
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger, IProductVMService productVMService)
        {
            _logger = logger;
            _productVMService = productVMService;
        }

        public ProductIndexVM ProductIndex { get; set; } = new ProductIndexVM();

        public void OnGet()
        {
            ProductIndex = _productVMService.GetProductsVM(HttpContext, null);
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BetterBuys/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using BetterBuys.Interfaces;
using BetterBuys.ViewModels;

namespace BetterBuys.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;
        private readonly IProductVMService _productVMService;

        public PrivacyModel(ILogger<PrivacyModel> logger,
            IProductVMService productVMService)
        {
            _logger = logger;
            _productVMService = productVMService;
        }

        public ProductIndexVM ProductIndex { get; set; } = new ProductIndexVM();

        public void OnGet()
        {
            ProductIndex = _productVMService.GetProductsVM(HttpContext, null);
        }
    }
}

BetterBuys/Pages/Product/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BetterBuys.Pages.IndividualProduct
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BetterBuys/Pages/Cart.cshtml
@page
@model BetterBuys.Pages.Cart.CartModel

@{
    decimal total = Model.CalTotal(Model.productsInCart);
}

<section class="shopping-cart wrapper">
    @if (Model.productsInCart.Count == 0)
    {
        <div class="empty-cart">
            <p>Your Cart Is Empty...</p>
            <a class="cont-shipping" asp-page="index">Continue Shopping</a>
        </div>
    }
    else
    {
        <div class="d-flex flex-wrap">
            <div class="d-flex flex-column cart-items align-items-center">
                @foreach (var item in Model.productsInCart)
                {
                    <partial name="_CartProductPartial" for="@item" />
                }
            </div>
            <div class="cart-receipt-container">

                <div class="promo" method="post">
                    <label for="promo-code" class="form-label">Add a Discount Code</label>
                    <div class="d-flex">
                        <input type="text" id="promo-code" class="col-form-control" />
                        <button class="promo-btn">Apply</button>
                    </div>
                </div>
                <div class="total text-center">
                    <div class="d-flex justify-content-between">
                        <p>Order Value</p>

                        <p>
                            $@string.Format("{0:n2}", total)
                        </p>
                    </div>
                    <div class="d-flex justify-content-between">
                        <p>Delivery</p>
                        <p>$8.00</p>
                    </div>
                    <hr />
                    <div class="d-flex justify-content-between total-price">
                        <b>Total</b>
                        <p>$@string.Format("{0:n2}", total + 8)</p>
                    </div>
                    <a class="cont-to-checkout" asp-page="Checkout">Continue To Checkout</a>
                    <small class="d-block">Prices and shipping costs are not confirmed until you've reached checkout</small>
                </div>
            </div>
        </div>
    }
</section>

BetterBuys/Pages/Checkout.cshtml
@page
@model BetterBuys.Pages.Checkout.CheckoutModel

@{
    decimal total = Model.CalTotal(Model.productsInCart);
}

<div class="checkout-content-wrapper">
    <div class="wrapper content-checkout">
        <div class="row my-3">
            @*shipping address box*@
            <div class="col-lg-6">
                <form class="form pr-lg-5 pb-5 pb-lg-0" method="post">
                    <h5 class="checkout-subtitile">Shipping Address</h5>
                    <div class="input-control firstName">
                        <input type="text" asp-for="@Model.FirstName" name="firstName" id="firstName" placeholder="First Name" />
                        <span asp-validation-for="@Model.FirstName" class="text-danger"></span>
                    </div>
                    <div class="input-control lastName">
                        <input type="text" asp-for="@Model.LastName" name="lastName" id="lastName" placeholder="Last Name" />
                        <span asp-validation-for="@Model.LastName" class="text-danger"></span>
                    </div>
                    <div class="input-control address">
                        <input type="text" asp-for="@Model.Address" name="address" id="address" placeholder="Adress" />
                        <span asp-validation-for="@Model.Address" class="text-danger"></span>
                    </div>
                    <div class="input-control apartment">
                        <input type="text" asp-for="@Model.Apartment" name="apartment" id="apartment" placeholder="Apartment (optional)" />
                        <span asp-validation-for="@Model.Apartment" class="text-danger"></span>
                    </div>
                    <div class="input-control city">
                        <input type="text" asp-for="@Model.City" name="city" id="city" placeholder="City" />
                        <span asp-validation-for="@Model.City" class="text-danger"></span>
                    </div>
                    @*<div class="d-flex">*@
                    <div class="input-control country">
                        <select asp-for="@Model.Country" name="country" class="countries" id="countryId">
                            <option value="">Select Country</option>
                            <option value="Canada">Canada</option>
                        </select>
                        <span asp-validation-for="@Model.Country" class="text-danger"></span>
                    </div>
                    <div class="input-control province">
                        <select asp-for="@Model.Province" name="province" class="provinces" id="provinceId">
                            <option value="">Select Province</option>
                            <option value="AB">Alberta</option>
                            <option value="BC">British Columbia</option>
                            <option value="MB">Manitoba</option>
                            <option value="NB">New Brunswick</option>
                            <option value="NL">Newfoundland and Labrador</option>
                            <option value="NS">Nova Scotia</option>
                            <option value="ON">Ontario</option>
                            <option value="PE">Prince Edward Island</option>
                            <option value="QC">Quebec</option>
                            <option value="SK">Saskatchewan</option>
                            <option value="NT">Northwest Territories</option>
                            <option value="NU">Nunavut</option>
                            <option value="YT">Yukon</option>
                        </select>
                        <span asp-validation-for="@Model.Province" class="text-danger"></span>
                    </div>
                    @*</div>*@
                    <div class="input-control postal">
                        <input type="text" asp-for="@Model.PostalCode" name="postalCode" id="postCode" placeholder="Postal Code" />
                        <span asp-validation-for="@Model.PostalCode" class="text-danger"></span>
                    </div>
                    <div class="input-control phone">
                        <input type="text" asp-for="@Model.Phone" name="phone" id="phone" placeholder="Phone" />
                        <span asp-validation-for="@Model.Phone" class="text-danger"></span>
                    </div>
                    <h5 class="checkout-subtitile">Payment Method</h5>
                    <div class="input-control name">
                        <input type="text" asp-for="@Model.CardHolderName" name="cardHolderName" id="name" placeholder="Cardholder Name" />
                        <span asp-validation-for="@Model.CardHolderName" class="text-danger"></span>
                    </div>
         
                    <div class="input-control number">
                        <input type="text" asp-for="@Model.CardNumber" name="cardNumber" id="number" placeholder="Card Number" />
                        <span asp-validation-for="@Model.CardNumber" class="text-danger"></span>
                    </div>
                    <div class="input-control expirationDate">
                        <input type="text" asp-for="@Model.ExpirationDate" name="expirationDate" id="expirationDate" placeholder="Expiration Date mm/yyyy" />
                        <span asp-validation-for="@Model.ExpirationDate" class="text-danger"></span>
                    </div>
                    @*</div>*@
                    <div class="bottom">
                        <input class="btn bottom-btn submit-btn" type="submit" value="COMPLETE PURCHASE" id="complete" />
                        <a class="bottom-btn" asp-page="cart">RETURN TO CART</a>
                    </div>
                </form>
            </div>
            @*order box*@
            <div class="order-box col-lg-6">
                <h5 class="checkout-subtitile-order">Order Summary</h5>
                @foreach (var item in Model.productsInCart)
                {
                    <div class="order-summary">
                        <div class="checkout-product-img">
                            <img src="@item.ImageUri" width="80" />
                            <div class="checkout-product-quantity">@item.Quantity</div>
                        </div>
                        <div class="checkout-product-name"><p>@item.Name</p></div>
                        <p class="checkout-product-price">$@string.Format("{0:n2}", item.Price * item.Quantity)</p>
                    </div>
                }

                <div class="order-detail">
                    <div class="promo" method="post">
                        <label for="promo-code" class="form-label">Add a Discount Code</label>
                        <div class="discount-box d-flex">
                            <input type="text" id="promo-code" class="col-form-control" />
                            <button class="promo-btn">Apply</button>
                        </div>
                    </div>
                    <div class="checkout-subtotal">
                        <p>Subtotal</p>
                        <p> $@string.Format("{0:n2}", total)</p>
                    </div>
                    <div class="checkout-delivery">
                        <p>Shipping</p>
                        <p>$8.00</p>
                    </div>
                    <div class="checkout-total">
                        <h5>Total</h5>
                        <h5>$@string.Format("{0:n2}", total + 8)</h5>
                    </div>
                    <small class="checkout-condition">Price and shipping costs are not confirmed until you've reached checkout</small>
                </div>
            </div>
        </div>
    </div>
</div>

BetterBuys/Pages/Confirmation.cshtml
@page
@model BetterBuys.Pages.ConfirmationModel
@{
}

<div class="wrapper confirmation-content">
    <h4 class="d-flex justify-content-center">Thank you for shopping at BetterBuys!</h4>    
    <a class="d-flex justify-content-center" asp-page="index">Return To Home</a>
</div>

BetterBuys/Pages/Detail.cshtml
@page
@model DetailModel

<section class="detail wrapper">
    <div class="product-detail-body">
        <div class="product-detail-img">
            <img src="@Model.ProductDetail.ImageUri" />
        </div>
        <div class="product-detail-body-text">
            <h5>@Model.ProductDetail.Name</h5>
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star"></i>
            <i class="fa fa-star-half"></i>
            <p>@Model.ProductDetail.Price.ToString("C")</p>
            <p>
                @Model.ProductDetail.Description
            </p>
            <form method="post">
                <div class="product-detail-button">
                    <div class="quantity">
                        <select class="form-control" input type="number" asp-for="@Model.ProductDetail.Quantity" name="quantity">
                            @for (int i = 1; i <= 10; i++)
                            {
                                <option>@i</option>
                            }
                        </select>
                    </div>
                    <div class="add-to-cart">
                        <input class="add-to-cart-btn" type="submit" value="Add to Cart" id="Add" />
                    </div>
                    @if (Model.warningMsg != "")
                    {
                        <p class="alert-danger quantity-alert">@Model.warningMsg</p>
                    }
                    <div class="product-detail-body-link">
                        <a asp-page="index" class="product-detail-link">Continue Shopping</a>
                    </div>
                </div>
                <input type="hidden" asp-for="@Model.ProductDetail.Id" name="id">
                <input type="hidden" asp-for="@Model.ProductDetail.Name" name="name">
                <input type="hidden" asp-for="@Model.ProductDetail.Price" name="price">
                <input type="hidden" asp-for="@Model.ProductDetail.ImageUri" name="pictureUri">
            </form>
        </div>
    </div>
</section>

BetterBuys/Pages/_CartProductPartial.cshtml
@model BetterBuys.ViewModels.ProductVM

<div class="cart-item d-flex">
    <div class="cart-img-container">
        <img src="@Model.ImageUri" />
    </div>
    <div class="d-flex cart-content">
        <form class="cart-form" method="post">
            <h5>@Model.Name</h5>
            <div class="cart-quantity-container">
                <select class="form-select cart-quantity-list" id="quantity" name="quantity">
                    @for (int i = 1; i < 51; i++)
                    {
                        @if (i == Model.Quantity)
                        {
                            <option value=@i selected>@i</option>
                        }
                        else
                        {
                            <option value=@i>@i</option>
                        }
                    }
                </select>
                <button class="cart-update-btn" type="submit" asp-page-handler="Update" asp-route-productId="@Model.Id">Update</button>
            </div>
            <p class="price">$@string.Format("{0:n2}", Model.Price * Model.Quantity)</p>
        </form>
        <form class="cart-delete-form" method="post">
            <button class="fas fa-times cart-item-delete"
               type="submit"
               asp-page-handler="Delete"
               asp-route-productId="@Model.Id"
               onclick="return confirm('Comfirm to Delete this item.')"></button>
        </form>
    </div>
</div>

BetterBuys/Pages/_ProductPartial.cshtml
@model BetterBuys.ViewModels.ProductVM

<div class="product-item-img">
    <a asp-page="/Detail" asp-route-productId="@Model.Id">
        <img src="@Model.ImageUri" alt="@Model.Name" />
    </a>
</div>
<form class="product-item-form" method="post">
    <div class="product-item-text">
        <p class="product-item-name">@Model.Name</p>
        <p class="product-item-price">$@string.Format("{0:n2}", Model.Price)</p>
        <button type="submit" class="product-item-add-btn">Add To Cart</button>
        <input type="hidden" asp-for="@Model.Id" name="id" />
        <input type="hidden" asp-for="@Model.Name" name="name" />
        <input type="hidden" asp-for="@Model.Price" name="price" />
        <input type="hidden" asp-for="@Model.ImageUri" name="pictureUri" />
        <input type="hidden" asp-for="@Model.Quantity" name="quantity" value="1" />
    </div>
</form>